export const ROUTES = {
  HOME: "/",
  PRODUCT: `/product`,
  CHECKOUT: "/checkout",
  PAYMENT: "/payment",
  CONTACT: "/contact-us",
  TERMS: "/terms",
  POLICY: "/privacy",
  FAQ: "/faq",
  FORGET_PASSWORD: "/forget-password",
  ACCOUNT: "/my-account",
  ORDERS: "/my-account/orders",
  ACCOUNT_DETAILS: "/my-account/account-details",
  CHANGE_PASSWORD: "/my-account/change-password",
  SHOPS: "/shops",
  TRACKING: "/tracking",
  LOGIN: "/signin",
  SIGN_UP: "/signup",
  SEARCH: "/search",
  COLLECTIONS: "/collections",
  CATEGORY: "/category",
  ORDER: "/order",
  DEALS: "/deals",
  NEWARRIVAL: "/new-arrivals",
  Thankyou: "/thankyou",
  BankTransfer: "/bank-transfer",
};
