// export const NO_SHIPPING_PRODUCTS: string[] = [

// ]

// export const SHOW_MINTPAY_PRODUCTS : string[] = [
//     "You are the One Valentine's Gift Box (FOR HIM)",
//     "You are the One Valentine's Gift Box (FOR HER)",
//     "Hugs & Kisses Valentine's Gift Box (FOR HIM)",
//     "Hugs & Kisses Valentine's Gift Box (FOR HER)",
//     "Test-1"
// ]

export const SHOW_MINTPAY_VENDORS: string[] = [
  "Anithya",
  "Royal Ceylon",
  "Lee's",
  "Sandalistik",
  "JAGS",
  "Ancient Nutra",
  "Hushele",
  "Rainco",
  "Pulse Active",
  "Ecobeam Lighting",
  "Z E R O",
  "Classy Missy",
  "Babysnmommys",
  "Groove Sri Lanka",
  "Curves",
  "Shilpa",
  "Posh Girls",
  "La Perfumerie.lk",
  "Figati Clothing",
  "Ceylonbig5",
  "Ayanthi",
  "FLECKLO",
  "Muse Ceylon",
  "VYAYA",
  "WEAD",
  "Petal Freeze",
  "Boost Buy.LK",
  "Aries Victoria",
  "TAAG Clothing",
  "Sublime Clothing",
  "Pureherbs Inventions",
  "Kaneliya fashion",
  "Aurelia Soapworks",
  "themagicpotionlk",
  "Outie Kids",
  "BOOloS",
  "Sheoly",
  "RUGA",
  "Gleenz.lk",
  "58 Division",
  "AVANTA Clothing",
  "Macks marketing pvt ltd",
  "Diya Kiduri",
  "Aadaraya Ceylon",
  "DTR Scrunchies",
  "Gimzaa",
  "Vigo",
  "Chakadi.lk",
  "Rough Clothing",
  "Stitch & Spark",
  "Quick Closet",
  "Lora & Leon",
  "Chakra LK",
  "Suwanda Industries (Pvt) Ltd",
  "Crafterina Resin jewellery",
];
