// // List of valid values
// export const VENDOR_LIST: string[] = [
//     "Lee's",
//     "Sandalistik",
//     "JAGS",
//     "Ancient Nutra",
//     "Hushele",
//     "Rainco",
//     "Pulse Active",
//     "Ecobeam Lighting",
//     "Z E R O",
//     "Classy Missy",
//     "Babysnmommys",
//     "Groove Sri Lanka",
//     "Chakadi.lk",
//     "Shilpa",
//     "Posh Girls",
//     "La Perfumerie.lk",
//     "Figati Clothing",
//     "Ceylonbig5",
//     "FLECKLO",
//     "Muse Ceylon",
//     "VYAYA",
//     "WEAD",
//     "Petal Freeze",
//     "Boost Buy.LK",
//     "Aries Victoria",
//     "TAAG Clothing",
//     "Sublime Clothing",
//     "Pureherbs Inventions",
//     "Kaneliya fashion",
//     "Aurelia Soapworks",
//     "Gimzaa",
//     "themagicpotionlk",
//     "Outie Kids",
//     "BOOloS",
//     "Rough Clothing",
//     "Sheoly",
//     "Crafterina Resin jewellery",
//     "RUGA",
//     "Gleenz.lk",
//     "58 Division"

//   ];
  